### PR TITLE
Removed TinyIoc and added Exception as input to IInternalLogger

### LINKED ISSUE #13: NLog can't parse configuration when adding Logzio as target in XML config
Hello,

NLog raises the following error when I try to add Logzio as target:
`rror Parsing configuration from *\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing *\NLog.config.  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.get_DeclaringType()
   at TinyIoC.TinyIoCContainer.<AutoRegisterInternal>b__112_2(Type type) in C:\dev\logzio-dotnet\src\Core\Bootstrap\TinyIoc.cs:line 3428
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TinyIoC.TinyIoCContainer.AutoRegisterInternal(IEnumerable`1 assemblies, DuplicateImplementationActions duplicateAction, Func`2 registrationPredicate) in C:\dev\logzio-dotnet\src\Core\Bootstrap\TinyIoc.cs:line 3427
   at TinyIoC.TinyIoCContainer.AutoRegister() in C:\dev\logzio-dotnet\src\Core\Bootstrap\TinyIoc.cs:line 1354
   at Logzio.DotNet.NLog.LogzioTarget..ctor() in C:\dev\logzio-dotnet\src\NLogShipper\LogzioTarget.cs:line 37
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NLog.Internal.FactoryHelper.CreateInstance(Type t)
   at NLog.Config.Factory`2.TryCreateInstance(String itemName, TBaseType& result)
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2018-07-16 19:19:22.3651 Warn NLog configuration while reloading Exception: NLog.NLogConfigurationException: Configuration.Reload() failed. Invalid XML?
   at NLog.LogFactory.ReloadConfigOnTimer(Object state)`

When I remove the target it works just fine.

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves  #13, but is a breaking change for those who depend on TinyIoc.

- Added debug logging to log4net internal logger
- Added debug logging to NLog internal logger

### CODE REVIEW

**Comment by idohalevi** [comment]
@snakefoot 
Can you specify the breaking changes?

**Comment by snakefoot** [comment]
People who uses IInternalLogger (Exception parameter added) or people who depends on TinyIOC (Removed)



Sent from my Samsung device


-------- Original message --------

**Comment by yellowblood** [comment]
@snakefoot correct me if I'm wrong, but you've added the internal logger to the customer's logging framework, which means they're going to need to filter it out if they upgrade/install the package. I don't like this at all - it's similar to what nHibernate does when you have a log4net in your application. You're forced to filter it out.

**Comment by snakefoot** [comment]
I'm only redirecting internal logging into the diagnostic logging of NLog and log4net.

It will not route into the normal Nlog-target or log4net-appenders of the customer

Just making this library integrate better with Nlog and log4net platforns




Sent from my Samsung device


-------- Original message --------

**Comment by snakefoot** [comment]
@idohalevi Could be nice to have this in ver. 1.0.2 and then unlist 1.0.1 (and 1.0.0). Since major version allows breaking change (especially in internal interfaces).

**Comment by snakefoot** [comment]
This looks really bad for the Log4net-Appender:

```
log4net:WARN Logzio: Couldn't handle log message
   System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
    at System.Collections.Hashtable.HashtableEnumerator.MoveNext()
    at Logzio.DotNet.Log4net.LogzioAppender.WriteImpl(LoggingEvent loggingEvent) in /home/travis/build/logzio/logzio-dotnet/src/Log4netShipper/LogzioAppender.cs:line 73
```

https://travis-ci.org/logzio/logzio-dotnet/builds/420591466

Maybe your use of Task.Run is not supported inside the log4net-appender?

**Comment by snakefoot** [comment]
@idohalevi When this has been resolved, then I can fix the NetStandard1.3 support

**Comment by yellowblood** [comment]
@snakefoot I'm still not sure it's a good approach, you're creating more coupling with the logging  framework - if we'll support other frameworks we'd have to implement the internal logger for these frameworks as well. If all you wanted was to add the exception, you can do that without the major changes.

**Comment by snakefoot** [comment]
What is the major change, besides removing TinyIOC ?



Sent from my Samsung device


-------- Original message --------

**Comment by yellowblood** [comment]
Alright, I'm convinced.

;)

**Comment by idohalevi** [comment]
@snakefoot approved, I'll wait for the NetStandard1.3 PR before releasing a new version

**Comment by snakefoot** [comment]
@idohalevi Created  #24 for NetStandard1.3 support

**Comment by idohalevi** [comment]
@snakefoot 
Thank you! I hope to get to it this week if not the beginning of next week

**Pull request merged**
