### PR TITLE
 LogzioTarget - Added support for contextproperty and flush in NLog 

### PR DESCRIPTION
**Pull request by snakefoot**
Also included some extra changes:

- BulkSender - Reduce allocations when serializing logevents
- LogzioAppender - Added support for Flush in log4net
- Nuget-packages - Fixed build-scripts to generate packages for NetStandard2.0 + net45

And also a breaking change by not including random "junk" found in NLog Global Configuration Variables. Instead one has to explicit include the wanted values using context-properties (updated documentation)

### CODE REVIEW

**Comment by snakefoot** [comment]
@idohalevi Any reason why you are not going all in on `dotnet pack` instead of still using nuget-spec ?

It would allow you to create an official nuget-package that supports both net45 + nestandard.

**Comment by snakefoot** [comment]
I have actually tried to follow the existing code style.

For some reason then BulkSender.cs , LogzioAppender.cs and LogzioTarget.cs are using tabs instead of spaces. Unit test cs files are correctly using spaces :)


Sent from my Samsung device


-------- Original message --------

**Comment by snakefoot** [comment]
@idohalevi Should I fix the coding styles for all files? Or do you want to do it yourself in a separate no-functional-change PR ?

**Comment by idohalevi** [comment]
@snakefoot 
If you can then please yes and I'll merge right after

**Comment by snakefoot** [comment]
@idohalevi Have now fixed the build-scripts so they use dotnet pack. Open a VS2017 `Developer Command Prompt` and execute these commands to build:

```
package\build-log4net.bat 0.3.0
package\build-nlog.bat 0.3.0
```

This will generate nuget-packages for log4net and NLog.

**Comment by snakefoot** [comment]
You need to navigate into the package-folder for the scripts to work.

I have created #18 that allows you run the script independent of your current folder.

**Comment by idohalevi** [comment]
@snakefoot 
Of course, I was referring to the example you gave, it looked like you are outside the package folder while the script required you to be in. :)

**Comment by snakefoot** [comment]
@idohalevi I just wanted to specify the actual path of the build-scripts.

**Pull request merged**
