### PR TITLE
Update nlog.md

### PR DESCRIPTION
**Pull request by boofinka**
Updated code shipping instructions to include

### CODE REVIEW

**Comment by idohalevi** [comment]
@imnotashrimp

**Comment by yyyogev** [comment]
@boofinka why did you removed the  proxy  address example?

**Comment by boofinka** [comment]
Sorry, my bad, must have missed it.

**Comment by snakefoot** [comment]
@boofinka Looks like the code will never compile. Have you just copied the XML-attribute values and used as csharp code ? (Since all values are in string-quotes).

**Comment by yyyogev** [comment]
moved  to https://github.com/logzio/logzio-dotnet/pull/46

**Pull request closed without merging**
